### ISSUE TITLE
twitter_user.rb error

### ISSUE THREAD

**Issue by ghost** [Ephigenia/foobugs-dashboard#13]
I tried to use the twitter_user.rb file but I receive this error. Is something not right?

scheduler caught exception:
undefined method `attributes' for nil:NilClass
/home/pi/manch/jobs/twitter_user.rb:14:in`block in <top (required)>'
/home/pi/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `call'
/home/pi/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in`trigger_block'
/home/pi/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:204:in `block in trigger'
/home/pi/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in`call'
/home/pi/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `block in trigger_job'

**Comment by mplewis** [comment]
I'm seeing the same issue.

**Comment by mplewis** [comment]
It looks like the issue is caused by Twitter changing their site layout. Replace lines 13 through 15 in `twitter_user.rb` with the following:

``` ruby
  tweets = doc.css('a[data-nav=tweets]').first.attributes['title'].value.split(' ').first
  followers = doc.css('a[data-nav=followers]').first.attributes['title'].value.split(' ').first
  following = doc.css('a[data-nav=following]').first.attributes['title'].value.split(' ').first
```

**Comment by Ephigenia** [comment]
@mplewis thanks for the hint, i hope that works fine. Twitter and the other services might change their markup from time to time.
