### ISSUE TITLE
foursquare job error

### ISSUE THREAD

**Issue by visibilityspots** [Ephigenia/foobugs-dashboard#5]
Hi I got this error when trying to use the foursquare plugin

I just copied the erb file into my dashboard-project/jobs/ directory

All other plugins are working fine, did I missed a step?

scheduler caught exception:
undefined method `[]' for nil:NilClass
*/jobs/foursquare_venue.rb:25:in`block in <top (required)>'

**Comment by Ephigenia** [comment]
I guess there’s something wrong when analyzing the scraped foursquare venue site. I’ll check that next week.

**Comment by visibilityspots** [comment]
Hi, in the meantime I figured out another approach to get the foursquare informations using their api => https://github.com/visibilityspots/dashing-scripts. That way you don't rely on the sites html code..

**Comment by nickste** [comment]
Foursquare (DE) changed the "Total Visitors" text on their site to "Besucher insgesamt". You can fix the foursquare.rb script by changing the following line (23) from:
checkins_people = /rightColumn.+Total Visitors.+venueStatCount.+data-count="([\d.,]+)">.+venueStatCount/
to
checkins_people = /rightColumn.+Besucher insgesamt.+venueStatCount.+data-count="([\d.,]+)">.+venueStatCount/

**Comment by Ephigenia** [comment]
@nickste thanks for the hint but maybe you want to change and test it yourself using the "edit" button on the file and and/or send a pull request with that change?

BTW: How do you test the dashboard? I’m having difficulties to run `dashing start` due to an issue in the event machine which is used and not compatible with the ruby i have on my max. Tipps appreciated.

```
/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/rubyeventmachine.bundle: [BUG] Segmentation fault
```

**Comment by nickste** [comment]
@Ephigenia I've edited/tested and submitted the pull request.

I can't seem to recreate the error you're receiving. Do you get the same error when you create a clean dashing project with `dashing new new_dash` ?

I'm using Ruby 2.0.0 and Rails 4.0.0

**Comment by Ephigenia** [comment]
@nickste thanks! I’ve managed to update my gems with `gem update --system` and after that I'm able to test the stuff again. I’ll check your pull request in the afternoon!
